name: aplikasi_umkm
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_xlsio: ^23.1.43
  syncfusion_flutter_pdf: ^23.1.43
  csv: ^5.0.1
  pdf: ^3.10.0
  printing: ^5.9.1
  open_file: ^3.3.1
  path_provider: ^2.1.5
  intl: ^0.18.0
  fl_chart: ^1.1.0
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.5
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  screenshot: ^3.0.0
  print_bluetooth_thermal: ^1.1.6
  esc_pos_utils_plus: ^2.0.4
  share_plus: ^11.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  barcode_widget: ^2.0.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_native_splash: ^2.4.0
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: 2.4.13
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mockito: ^5.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Flutter Native Splash Configuration
flutter_native_splash:
  # Background color (gunakan warna brand Pelindo atau putih)
  color: "#FFFFFF"

  # Logo utama
  image: assets/images/logo_pelindo.png

  # Logo untuk dark mode (opsional, bisa sama dengan image)
  image_dark: assets/images/logo_pelindo.png

  # Pengaturan fullscreen untuk mencegah crop
  fullscreen: true

  # Pengaturan Android
  android: true
  android_gravity: center
  android_lottie: false

  # Pengaturan iOS
  ios: true
  ios_content_mode: center

  # Pengaturan Web (opsional)
  web: true

  # Konfigurasi khusus Android 12+
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo_pelindo.png
    icon_background_color: "#FFFFFF"
    # Untuk Android 12, pastikan logo tidak terlalu besar
    # Ukuran maksimal yang disarankan: 288dp x 288dp
